//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/planner/operator/list.hpp"
#include "duckdb/catalog/catalog_entry/schema_catalog_entry.hpp"
#include "duckdb/catalog/catalog_entry/table_catalog_entry.hpp"
#include "duckdb/planner/operator/logical_external_resource.hpp"

namespace duckdb {

void LogicalOperator::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<LogicalOperatorType>(100, "type", type);
	serializer.WritePropertyWithDefault<vector<unique_ptr<LogicalOperator>>>(101, "children", children);
}

unique_ptr<LogicalOperator> LogicalOperator::Deserialize(Deserializer &deserializer) {
	auto type = deserializer.ReadProperty<LogicalOperatorType>(100, "type");
	auto children = deserializer.ReadPropertyWithDefault<vector<unique_ptr<LogicalOperator>>>(101, "children");
	deserializer.Set<LogicalOperatorType>(type);
	unique_ptr<LogicalOperator> result;
	switch (type) {
	case LogicalOperatorType::LOGICAL_AGGREGATE_AND_GROUP_BY:
		result = LogicalAggregate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_ALTER:
		result = LogicalAlter::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_ANY_JOIN:
		result = LogicalAnyJoin::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_ASOF_JOIN:
		result = LogicalComparisonJoin::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_ATTACH:
		result = LogicalAttach::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CHUNK_GET:
		result = LogicalColumnDataGet::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_COMPARISON_JOIN:
		result = LogicalComparisonJoin::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CONNECT:
		result = LogicalConnect::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_COPY_DATABASE:
		result = LogicalCopyDatabase::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_COPY_TO_FILE:
		result = LogicalCopyToFile::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_INDEX:
		result = LogicalCreateIndex::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_MACRO:
		result = LogicalCreate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_SCHEMA:
		result = LogicalCreate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_SEQUENCE:
		result = LogicalCreate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_TABLE:
		result = LogicalCreateTable::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_TRIGGER:
		result = LogicalCreate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_TYPE:
		result = LogicalCreate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CREATE_VIEW:
		result = LogicalCreate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CROSS_PRODUCT:
		result = LogicalCrossProduct::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_CTE_REF:
		result = LogicalCTERef::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DELETE:
		result = LogicalDelete::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DELIM_GET:
		result = LogicalDelimGet::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DELIM_JOIN:
		result = LogicalComparisonJoin::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DETACH:
		result = LogicalDetach::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DISCONNECT:
		result = LogicalDisconnect::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DISTINCT:
		result = LogicalDistinct::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DROP:
		result = LogicalDrop::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_DUMMY_SCAN:
		result = LogicalDummyScan::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EMPTY_RESULT:
		result = LogicalEmptyResult::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EXCEPT:
		result = LogicalSetOperation::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EXPLAIN:
		result = LogicalExplain::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EXPORT:
		result = LogicalExport::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EXPRESSION_GET:
		result = LogicalExpressionGet::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EXTENSION_OPERATOR:
		result = LogicalExtensionOperator::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_EXTERNAL_RESOURCE:
		result = LogicalExternalResource::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_FILTER:
		result = LogicalFilter::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_GET:
		result = LogicalGet::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_GROUP_JOIN:
		result = LogicalGroupJoin::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_INSERT:
		result = LogicalInsert::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_INTERSECT:
		result = LogicalSetOperation::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_LIMIT:
		result = LogicalLimit::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_LOAD:
		result = LogicalLoad::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_MATERIALIZED_CTE:
		result = LogicalMaterializedCTE::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_MERGE_INTO:
		result = LogicalMergeInto::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_ORDER_BY:
		result = LogicalOrder::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_PIVOT:
		result = LogicalPivot::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_POSITIONAL_JOIN:
		result = LogicalPositionalJoin::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_PROJECTION:
		result = LogicalProjection::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_RECURSIVE_CTE:
		result = LogicalRecursiveCTE::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_RESET:
		result = LogicalReset::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_SAMPLE:
		result = LogicalSample::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_SET:
		result = LogicalSet::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_TOP_N:
		result = LogicalTopN::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_TRANSACTION:
		result = LogicalTransaction::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_UNION:
		result = LogicalSetOperation::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_UNNEST:
		result = LogicalUnnest::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_UPDATE:
		result = LogicalUpdate::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_VACUUM:
		result = LogicalVacuum::Deserialize(deserializer);
		break;
	case LogicalOperatorType::LOGICAL_WINDOW:
		result = LogicalWindow::Deserialize(deserializer);
		break;
	default:
		throw SerializationException("Unsupported type for deserialization of LogicalOperator!");
	}
	deserializer.Unset<LogicalOperatorType>();
	result->children = std::move(children);
	if (type == LogicalOperatorType::LOGICAL_UPDATE) {
		LogicalUpdate::RewriteInPlaceUpdates(*result);
	}
	return result;
}

void BoundMergeIntoAction::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<MergeActionType>(200, "action_type", action_type);
	serializer.WritePropertyWithDefault<unique_ptr<Expression>>(201, "condition", condition);
	serializer.WritePropertyWithDefault<vector<PhysicalIndex>>(202, "columns", columns);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(203, "expressions", expressions);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<IndexVector<idx_t, PhysicalIndex>>(204, "column_index_map", column_index_map, IndexVector<idx_t, PhysicalIndex>());
	} else {
		serializer.WriteProperty<IndexVector<idx_t, PhysicalIndex>>(204, "column_index_map", column_index_map);
	}
	serializer.WritePropertyWithDefault<bool>(205, "update_is_del_and_insert", update_is_del_and_insert);
}

unique_ptr<BoundMergeIntoAction> BoundMergeIntoAction::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<BoundMergeIntoAction>(new BoundMergeIntoAction());
	deserializer.ReadProperty<MergeActionType>(200, "action_type", result->action_type);
	deserializer.ReadPropertyWithDefault<unique_ptr<Expression>>(201, "condition", result->condition);
	deserializer.ReadPropertyWithDefault<vector<PhysicalIndex>>(202, "columns", result->columns);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(203, "expressions", result->expressions);
	deserializer.ReadPropertyWithExplicitDefault<IndexVector<idx_t, PhysicalIndex>>(204, "column_index_map", result->column_index_map, IndexVector<idx_t, PhysicalIndex>());
	deserializer.ReadPropertyWithDefault<bool>(205, "update_is_del_and_insert", result->update_is_del_and_insert);
	return result;
}

void FileNameSegment::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<FileNameSegmentType>(200, "type", type);
	serializer.WritePropertyWithDefault<string>(201, "data", data);
}

FileNameSegment FileNameSegment::Deserialize(Deserializer &deserializer) {
	FileNameSegment result;
	deserializer.ReadProperty<FileNameSegmentType>(200, "type", result.type);
	deserializer.ReadPropertyWithDefault<string>(201, "data", result.data);
	return result;
}

void FilenamePattern::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<string>(200, "base", SerializeBase());
	serializer.WritePropertyWithDefault<idx_t>(201, "pos", SerializePos());
	serializer.WritePropertyWithDefault<bool>(202, "uuid", HasUUID());
	serializer.WritePropertyWithDefault<vector<FileNameSegment>>(203, "segments", SerializeSegments());
}

FilenamePattern FilenamePattern::Deserialize(Deserializer &deserializer) {
	auto base = deserializer.ReadPropertyWithDefault<string>(200, "base");
	auto pos = deserializer.ReadPropertyWithDefault<idx_t>(201, "pos");
	auto uuid = deserializer.ReadPropertyWithDefault<bool>(202, "uuid");
	auto segments = deserializer.ReadPropertyWithDefault<vector<FileNameSegment>>(203, "segments");
	FilenamePattern result(std::move(base), pos, uuid, std::move(segments));
	return result;
}

void LogicalAggregate::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(200, "expressions", expressions);
	serializer.WritePropertyWithDefault<TableIndex>(201, "group_index", group_index);
	serializer.WritePropertyWithDefault<TableIndex>(202, "aggregate_index", aggregate_index);
	serializer.WritePropertyWithDefault<TableIndex>(203, "groupings_index", groupings_index);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(204, "groups", groups);
	serializer.WritePropertyWithDefault<vector<GroupingSet>>(205, "grouping_sets", grouping_sets);
	serializer.WritePropertyWithDefault<vector<unsafe_vector<ProjectionIndex>>>(206, "grouping_functions", grouping_functions);
	serializer.WritePropertyWithDefault<TupleDataValidityType>(207, "distinct_validity", distinct_validity, TupleDataValidityType::CAN_HAVE_NULL_VALUES);
	serializer.WritePropertyWithDefault<bool>(208, "group_join_auto_selected", group_join_auto_selected, false);
	serializer.WritePropertyWithDefault<bool>(209, "group_join_auto_index", group_join_auto_index, false);
}

unique_ptr<LogicalOperator> LogicalAggregate::Deserialize(Deserializer &deserializer) {
	auto expressions = deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(200, "expressions");
	auto group_index = deserializer.ReadPropertyWithDefault<TableIndex>(201, "group_index");
	auto aggregate_index = deserializer.ReadPropertyWithDefault<TableIndex>(202, "aggregate_index");
	auto result = duckdb::unique_ptr<LogicalAggregate>(new LogicalAggregate(group_index, aggregate_index, std::move(expressions)));
	deserializer.ReadPropertyWithDefault<TableIndex>(203, "groupings_index", result->groupings_index);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(204, "groups", result->groups);
	deserializer.ReadPropertyWithDefault<vector<GroupingSet>>(205, "grouping_sets", result->grouping_sets);
	deserializer.ReadPropertyWithDefault<vector<unsafe_vector<ProjectionIndex>>>(206, "grouping_functions", result->grouping_functions);
	deserializer.ReadPropertyWithExplicitDefault<TupleDataValidityType>(207, "distinct_validity", result->distinct_validity, TupleDataValidityType::CAN_HAVE_NULL_VALUES);
	deserializer.ReadPropertyWithExplicitDefault<bool>(208, "group_join_auto_selected", result->group_join_auto_selected, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(209, "group_join_auto_index", result->group_join_auto_index, false);
	return std::move(result);
}

void LogicalAlter::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<AlterInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalAlter::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalAlter>(new LogicalAlter(std::move(info)));
	return std::move(result);
}

void LogicalAnyJoin::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WriteProperty<JoinType>(200, "join_type", join_type);
	serializer.WritePropertyWithDefault<TableIndex>(201, "mark_index", mark_index);
	serializer.WritePropertyWithDefault<vector<ProjectionIndex>>(202, "left_projection_map", left_projection_map);
	serializer.WritePropertyWithDefault<vector<ProjectionIndex>>(203, "right_projection_map", right_projection_map);
	serializer.WritePropertyWithDefault<unique_ptr<Expression>>(204, "condition", condition);
}

unique_ptr<LogicalOperator> LogicalAnyJoin::Deserialize(Deserializer &deserializer) {
	auto join_type = deserializer.ReadProperty<JoinType>(200, "join_type");
	auto result = duckdb::unique_ptr<LogicalAnyJoin>(new LogicalAnyJoin(join_type));
	deserializer.ReadPropertyWithDefault<TableIndex>(201, "mark_index", result->mark_index);
	deserializer.ReadPropertyWithDefault<vector<ProjectionIndex>>(202, "left_projection_map", result->left_projection_map);
	deserializer.ReadPropertyWithDefault<vector<ProjectionIndex>>(203, "right_projection_map", result->right_projection_map);
	deserializer.ReadPropertyWithDefault<unique_ptr<Expression>>(204, "condition", result->condition);
	return std::move(result);
}

void LogicalAttach::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<AttachInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalAttach::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalAttach>(new LogicalAttach(std::move(info)));
	return std::move(result);
}

void LogicalCTERef::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
	serializer.WritePropertyWithDefault<TableIndex>(201, "cte_index", cte_index);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(202, "chunk_types", chunk_types);
	serializer.WritePropertyWithDefault<vector<Identifier>>(203, "bound_columns", bound_columns);
	/* [Deleted] (CTEMaterialize) "materialized_cte" */
	serializer.WritePropertyWithDefault<bool>(205, "is_recurring", is_recurring);
}

unique_ptr<LogicalOperator> LogicalCTERef::Deserialize(Deserializer &deserializer) {
	auto table_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index");
	auto cte_index = deserializer.ReadPropertyWithDefault<TableIndex>(201, "cte_index");
	auto chunk_types = deserializer.ReadPropertyWithDefault<vector<LogicalType>>(202, "chunk_types");
	auto bound_columns = deserializer.ReadPropertyWithDefault<vector<Identifier>>(203, "bound_columns");
	auto result = duckdb::unique_ptr<LogicalCTERef>(new LogicalCTERef(table_index, cte_index, std::move(chunk_types), std::move(bound_columns)));
	deserializer.ReadDeletedProperty<CTEMaterialize>(204, "materialized_cte");
	deserializer.ReadPropertyWithDefault<bool>(205, "is_recurring", result->is_recurring);
	return std::move(result);
}

void LogicalComparisonJoin::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WriteProperty<JoinType>(200, "join_type", join_type);
	serializer.WritePropertyWithDefault<TableIndex>(201, "mark_index", mark_index);
	serializer.WritePropertyWithDefault<vector<ProjectionIndex>>(202, "left_projection_map", left_projection_map);
	serializer.WritePropertyWithDefault<vector<ProjectionIndex>>(203, "right_projection_map", right_projection_map);
	serializer.WritePropertyWithDefault<vector<JoinCondition>>(204, "conditions", conditions);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(205, "mark_types", mark_types);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(206, "duplicate_eliminated_columns", duplicate_eliminated_columns);
	serializer.WritePropertyWithDefault<bool>(207, "delim_flipped", delim_flipped, false);
	/* [Deleted] (unique_ptr<Expression>) "predicate" */
}

unique_ptr<LogicalOperator> LogicalComparisonJoin::Deserialize(Deserializer &deserializer) {
	auto join_type = deserializer.ReadProperty<JoinType>(200, "join_type");
	auto result = duckdb::unique_ptr<LogicalComparisonJoin>(new LogicalComparisonJoin(join_type, deserializer.Get<LogicalOperatorType>()));
	deserializer.ReadPropertyWithDefault<TableIndex>(201, "mark_index", result->mark_index);
	deserializer.ReadPropertyWithDefault<vector<ProjectionIndex>>(202, "left_projection_map", result->left_projection_map);
	deserializer.ReadPropertyWithDefault<vector<ProjectionIndex>>(203, "right_projection_map", result->right_projection_map);
	deserializer.ReadPropertyWithDefault<vector<JoinCondition>>(204, "conditions", result->conditions);
	deserializer.ReadPropertyWithDefault<vector<LogicalType>>(205, "mark_types", result->mark_types);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(206, "duplicate_eliminated_columns", result->duplicate_eliminated_columns);
	deserializer.ReadPropertyWithExplicitDefault<bool>(207, "delim_flipped", result->delim_flipped, false);
	deserializer.ReadDeletedProperty<unique_ptr<Expression>>(208, "predicate");
	return std::move(result);
}

void LogicalConnect::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<ConnectInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalConnect::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalConnect>(new LogicalConnect(std::move(info)));
	return std::move(result);
}

void LogicalCopyDatabase::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CopyDatabaseInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalCopyDatabase::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalCopyDatabase>(new LogicalCopyDatabase(std::move(info)));
	return std::move(result);
}

void LogicalCreate::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalCreate::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalCreate>(new LogicalCreate(deserializer.Get<LogicalOperatorType>(), deserializer.Get<ClientContext &>(), std::move(info)));
	return std::move(result);
}

void LogicalCreateIndex::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateIndexInfo>>(200, "info", info);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(201, "unbound_expressions", unbound_expressions);
	serializer.WritePropertyWithDefault<unique_ptr<AlterTableInfo>>(202, "alter_table_info", alter_table_info);
}

unique_ptr<LogicalOperator> LogicalCreateIndex::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "info");
	auto unbound_expressions = deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(201, "unbound_expressions");
	auto alter_table_info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(202, "alter_table_info");
	auto result = duckdb::unique_ptr<LogicalCreateIndex>(new LogicalCreateIndex(deserializer.Get<ClientContext &>(), std::move(info), std::move(unbound_expressions), std::move(alter_table_info)));
	return std::move(result);
}

void LogicalCreateTable::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(200, "info", info->base);
}

unique_ptr<LogicalOperator> LogicalCreateTable::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalCreateTable>(new LogicalCreateTable(deserializer.Get<ClientContext &>(), std::move(info)));
	return std::move(result);
}

void LogicalCrossProduct::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
}

unique_ptr<LogicalOperator> LogicalCrossProduct::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalCrossProduct>(new LogicalCrossProduct());
	return std::move(result);
}

void LogicalDelete::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info", table.GetInfo());
	serializer.WritePropertyWithDefault<TableIndex>(201, "table_index", table_index);
	serializer.WritePropertyWithDefault<bool>(202, "return_chunk", return_chunk);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(203, "expressions", expressions);
	serializer.WritePropertyWithDefault<vector<idx_t>>(204, "return_columns", return_columns);
}

unique_ptr<LogicalOperator> LogicalDelete::Deserialize(Deserializer &deserializer) {
	auto table_info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info");
	auto result = duckdb::unique_ptr<LogicalDelete>(new LogicalDelete(deserializer.Get<ClientContext &>(), table_info));
	deserializer.ReadPropertyWithDefault<TableIndex>(201, "table_index", result->table_index);
	deserializer.ReadPropertyWithDefault<bool>(202, "return_chunk", result->return_chunk);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(203, "expressions", result->expressions);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(204, "return_columns", result->return_columns);
	return std::move(result);
}

void LogicalDelimGet::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(201, "chunk_types", chunk_types);
}

unique_ptr<LogicalOperator> LogicalDelimGet::Deserialize(Deserializer &deserializer) {
	auto table_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index");
	auto chunk_types = deserializer.ReadPropertyWithDefault<vector<LogicalType>>(201, "chunk_types");
	auto result = duckdb::unique_ptr<LogicalDelimGet>(new LogicalDelimGet(table_index, std::move(chunk_types)));
	return std::move(result);
}

void LogicalDetach::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<DetachInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalDetach::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalDetach>(new LogicalDetach(std::move(info)));
	return std::move(result);
}

void LogicalDisconnect::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<DisconnectInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalDisconnect::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalDisconnect>(new LogicalDisconnect(std::move(info)));
	return std::move(result);
}

void LogicalDistinct::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WriteProperty<DistinctType>(200, "distinct_type", distinct_type);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(201, "distinct_targets", distinct_targets);
	serializer.WritePropertyWithDefault<unique_ptr<BoundOrderModifier>>(202, "order_by", order_by);
}

unique_ptr<LogicalOperator> LogicalDistinct::Deserialize(Deserializer &deserializer) {
	auto distinct_type = deserializer.ReadProperty<DistinctType>(200, "distinct_type");
	auto distinct_targets = deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(201, "distinct_targets");
	auto result = duckdb::unique_ptr<LogicalDistinct>(new LogicalDistinct(std::move(distinct_targets), distinct_type));
	deserializer.ReadPropertyWithDefault<unique_ptr<BoundOrderModifier>>(202, "order_by", result->order_by);
	return std::move(result);
}

void LogicalDrop::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<DropInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalDrop::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalDrop>(new LogicalDrop(std::move(info)));
	return std::move(result);
}

void LogicalDummyScan::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
}

unique_ptr<LogicalOperator> LogicalDummyScan::Deserialize(Deserializer &deserializer) {
	auto table_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index");
	auto result = duckdb::unique_ptr<LogicalDummyScan>(new LogicalDummyScan(table_index));
	return std::move(result);
}

void LogicalEmptyResult::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(200, "return_types", return_types);
	serializer.WritePropertyWithDefault<vector<ColumnBinding>>(201, "bindings", bindings);
}

unique_ptr<LogicalOperator> LogicalEmptyResult::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalEmptyResult>(new LogicalEmptyResult());
	deserializer.ReadPropertyWithDefault<vector<LogicalType>>(200, "return_types", result->return_types);
	deserializer.ReadPropertyWithDefault<vector<ColumnBinding>>(201, "bindings", result->bindings);
	return std::move(result);
}

void LogicalExplain::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WriteProperty<ExplainType>(200, "explain_type", explain_type);
	serializer.WritePropertyWithDefault<string>(201, "physical_plan", physical_plan);
	serializer.WritePropertyWithDefault<string>(202, "logical_plan_unopt", logical_plan_unopt);
	serializer.WritePropertyWithDefault<string>(203, "logical_plan_opt", logical_plan_opt);
}

unique_ptr<LogicalOperator> LogicalExplain::Deserialize(Deserializer &deserializer) {
	auto explain_type = deserializer.ReadProperty<ExplainType>(200, "explain_type");
	auto result = duckdb::unique_ptr<LogicalExplain>(new LogicalExplain(explain_type));
	deserializer.ReadPropertyWithDefault<string>(201, "physical_plan", result->physical_plan);
	deserializer.ReadPropertyWithDefault<string>(202, "logical_plan_unopt", result->logical_plan_unopt);
	deserializer.ReadPropertyWithDefault<string>(203, "logical_plan_opt", result->logical_plan_opt);
	return std::move(result);
}

void LogicalExport::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CopyInfo>>(200, "copy_info", copy_info);
	serializer.WritePropertyWithDefault<unique_ptr<BoundExportData>>(201, "exported_tables", exported_tables);
}

unique_ptr<LogicalOperator> LogicalExport::Deserialize(Deserializer &deserializer) {
	auto copy_info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "copy_info");
	auto exported_tables = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(201, "exported_tables");
	auto result = duckdb::unique_ptr<LogicalExport>(new LogicalExport(deserializer.Get<ClientContext &>(), std::move(copy_info), std::move(exported_tables)));
	return std::move(result);
}

void LogicalExpressionGet::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(201, "expr_types", expr_types);
	serializer.WritePropertyWithDefault<vector<vector<unique_ptr<Expression>>>>(202, "expressions", expressions);
}

unique_ptr<LogicalOperator> LogicalExpressionGet::Deserialize(Deserializer &deserializer) {
	auto table_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index");
	auto expr_types = deserializer.ReadPropertyWithDefault<vector<LogicalType>>(201, "expr_types");
	auto expressions = deserializer.ReadPropertyWithDefault<vector<vector<unique_ptr<Expression>>>>(202, "expressions");
	auto result = duckdb::unique_ptr<LogicalExpressionGet>(new LogicalExpressionGet(table_index, std::move(expr_types), std::move(expressions)));
	return std::move(result);
}

void LogicalExternalResource::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WriteProperty<BoundExternalResource>(200, "data", data);
}

unique_ptr<LogicalOperator> LogicalExternalResource::Deserialize(Deserializer &deserializer) {
	auto data = deserializer.ReadProperty<BoundExternalResource>(200, "data");
	auto result = duckdb::unique_ptr<LogicalExternalResource>(new LogicalExternalResource(data));
	return std::move(result);
}

void LogicalFilter::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(200, "expressions", expressions);
	serializer.WritePropertyWithDefault<vector<ProjectionIndex>>(201, "projection_map", projection_map);
}

unique_ptr<LogicalOperator> LogicalFilter::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalFilter>(new LogicalFilter());
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(200, "expressions", result->expressions);
	deserializer.ReadPropertyWithDefault<vector<ProjectionIndex>>(201, "projection_map", result->projection_map);
	return std::move(result);
}

void LogicalGroupJoin::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(200, "expressions", expressions);
	serializer.WritePropertyWithDefault<TableIndex>(201, "group_index", group_index);
	serializer.WritePropertyWithDefault<TableIndex>(202, "aggregate_index", aggregate_index);
	serializer.WritePropertyWithDefault<TableIndex>(203, "groupings_index", groupings_index);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(204, "groups", groups);
	serializer.WritePropertyWithDefault<vector<GroupingSet>>(205, "grouping_sets", grouping_sets);
	serializer.WritePropertyWithDefault<vector<unsafe_vector<ProjectionIndex>>>(206, "grouping_functions", grouping_functions);
	serializer.WritePropertyWithDefault<TupleDataValidityType>(207, "distinct_validity", distinct_validity, TupleDataValidityType::CAN_HAVE_NULL_VALUES);
	serializer.WritePropertyWithDefault<idx_t>(208, "owner_child", owner_child);
	serializer.WritePropertyWithDefault<idx_t>(209, "probe_child", probe_child);
	serializer.WritePropertyWithDefault<idx_t>(210, "left_column_count", left_column_count);
	serializer.WritePropertyWithDefault<vector<idx_t>>(211, "owner_key_indices", owner_key_indices);
	serializer.WritePropertyWithDefault<vector<idx_t>>(212, "probe_key_indices", probe_key_indices);
	serializer.WritePropertyWithDefault<vector<idx_t>>(213, "owner_payload_indices", owner_payload_indices);
	serializer.WritePropertyWithDefault<vector<HashGroupJoinOutputSource>>(214, "output_group_sources", output_group_sources);
	serializer.WritePropertyWithDefault<vector<idx_t>>(215, "output_group_indices", output_group_indices);
	serializer.WriteProperty<HashGroupJoinUnmatchedPolicy>(216, "unmatched_policy", unmatched_policy);
	serializer.WritePropertyWithDefault<bool>(217, "routed", routed, false);
	serializer.WritePropertyWithDefault<bool>(218, "unique_owner", unique_owner, false);
	serializer.WritePropertyWithDefault<bool>(219, "single_match", single_match, false);
	serializer.WritePropertyWithDefault<bool>(220, "use_index", implementation == GroupJoinImplementation::INDEX, false);
	serializer.WritePropertyWithDefault<GroupJoinExecutionMode>(221, "execution_mode", execution_mode, GroupJoinExecutionMode::AUTO);
	serializer.WritePropertyWithDefault<idx_t>(222, "estimated_owner_rows", estimated_owner_rows, 0);
	serializer.WritePropertyWithDefault<idx_t>(223, "estimated_probe_rows", estimated_probe_rows, 0);
	serializer.WritePropertyWithDefault<idx_t>(224, "estimated_match_rows", estimated_match_rows, 0);
	serializer.WritePropertyWithDefault<idx_t>(225, "estimated_matched_groups", estimated_matched_groups, 0);
	serializer.WritePropertyWithDefault<idx_t>(226, "estimated_distinct_probe_keys", estimated_distinct_probe_keys, 0);
	serializer.WritePropertyWithDefault<double>(227, "separate_cost", separate_cost, 0);
	serializer.WritePropertyWithDefault<double>(228, "eager_cost", eager_cost, 0);
	serializer.WritePropertyWithDefault<double>(229, "memoizing_cost", memoizing_cost, 0);
	serializer.WritePropertyWithDefault<double>(230, "index_cost", index_cost, 0);
	serializer.WritePropertyWithDefault<Value>(231, "perfect_min", perfect_min, Value());
	serializer.WritePropertyWithDefault<Value>(232, "perfect_max", perfect_max, Value());
	serializer.WritePropertyWithDefault<idx_t>(233, "perfect_range", perfect_range, 0);
	serializer.WritePropertyWithDefault<double>(234, "physical_eager_cost", physical_eager_cost, 0);
	serializer.WritePropertyWithDefault<GroupJoinImplementation>(235, "implementation", implementation, GroupJoinImplementation::MEMOIZING_HASH);
	serializer.WritePropertyWithDefault<double>(236, "perfect_cost", perfect_cost, 0);
	serializer.WritePropertyWithDefault<vector<idx_t>>(237, "factorized_driver_key_indices", factorized_driver_key_indices, {});
	serializer.WritePropertyWithDefault<vector<idx_t>>(238, "factorized_left_key_indices", factorized_left_key_indices, {});
	serializer.WritePropertyWithDefault<vector<idx_t>>(239, "factorized_right_key_indices", factorized_right_key_indices, {});
	serializer.WritePropertyWithDefault<vector<FactorizedAggregateSource>>(240, "factorized_aggregate_sources", factorized_aggregate_sources, {});
	serializer.WritePropertyWithDefault<idx_t>(241, "factorized_driver_column_count", factorized_driver_column_count, 0);
	serializer.WritePropertyWithDefault<idx_t>(242, "factorized_left_column_count", factorized_left_column_count, 0);
	serializer.WritePropertyWithDefault<idx_t>(243, "estimated_left_factor_rows", estimated_left_factor_rows, 0);
	serializer.WritePropertyWithDefault<idx_t>(244, "estimated_right_factor_rows", estimated_right_factor_rows, 0);
	serializer.WritePropertyWithDefault<bool>(245, "factorized_preserve_left", factorized_preserve_left, false);
	serializer.WritePropertyWithDefault<bool>(246, "factorized_preserve_right", factorized_preserve_right, false);
	serializer.WritePropertyWithDefault<bool>(247, "factorized_semi_left", factorized_semi_left, false);
	serializer.WritePropertyWithDefault<bool>(248, "factorized_semi_right", factorized_semi_right, false);
	serializer.WritePropertyWithDefault<idx_t>(249, "estimated_factorized_join_rows", estimated_factorized_join_rows, 0);
	serializer.WritePropertyWithDefault<idx_t>(250, "estimated_factorized_matched_drivers", estimated_factorized_matched_drivers, 0);
	serializer.WritePropertyWithDefault<idx_t>(251, "estimated_left_factor_scan_rows", estimated_left_factor_scan_rows, 0);
	serializer.WritePropertyWithDefault<idx_t>(252, "estimated_right_factor_scan_rows", estimated_right_factor_scan_rows, 0);
	serializer.WritePropertyWithDefault<double>(253, "factorized_build_cost", factorized_build_cost, 0);
	serializer.WritePropertyWithDefault<double>(254, "factorized_probe_cost", factorized_probe_cost, 0);
	serializer.WritePropertyWithDefault<double>(255, "factorized_scan_cost", factorized_scan_cost, 0);
	serializer.WritePropertyWithDefault<double>(256, "factorized_routing_cost", factorized_routing_cost, 0);
	serializer.WritePropertyWithDefault<double>(257, "factorized_spill_cost", factorized_spill_cost, 0);
	serializer.WritePropertyWithDefault<double>(258, "factorized_cost", factorized_cost, 0);
	serializer.WritePropertyWithDefault<double>(259, "factorized_best_existing_cost", factorized_best_existing_cost, 0);
	serializer.WritePropertyWithDefault<bool>(260, "factorized_cost_reliable", factorized_cost_reliable, false);
	serializer.WritePropertyWithDefault<bool>(261, "factorized_auto_selected", factorized_auto_selected, false);
	serializer.WritePropertyWithDefault<double>(262, "factorized_filter_cost", factorized_filter_cost, 0);
	serializer.WritePropertyWithDefault<double>(263, "factorized_cache_cost", factorized_cache_cost, 0);
	serializer.WritePropertyWithDefault<double>(264, "factorized_eager_work_cost", factorized_eager_work_cost, 0);
}

unique_ptr<LogicalOperator> LogicalGroupJoin::Deserialize(Deserializer &deserializer) {
	auto expressions = deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(200, "expressions");
	auto group_index = deserializer.ReadPropertyWithDefault<TableIndex>(201, "group_index");
	auto aggregate_index = deserializer.ReadPropertyWithDefault<TableIndex>(202, "aggregate_index");
	auto result = duckdb::unique_ptr<LogicalGroupJoin>(new LogicalGroupJoin(group_index, aggregate_index, std::move(expressions)));
	deserializer.ReadPropertyWithDefault<TableIndex>(203, "groupings_index", result->groupings_index);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(204, "groups", result->groups);
	deserializer.ReadPropertyWithDefault<vector<GroupingSet>>(205, "grouping_sets", result->grouping_sets);
	deserializer.ReadPropertyWithDefault<vector<unsafe_vector<ProjectionIndex>>>(206, "grouping_functions", result->grouping_functions);
	deserializer.ReadPropertyWithExplicitDefault<TupleDataValidityType>(207, "distinct_validity", result->distinct_validity, TupleDataValidityType::CAN_HAVE_NULL_VALUES);
	deserializer.ReadPropertyWithDefault<idx_t>(208, "owner_child", result->owner_child);
	deserializer.ReadPropertyWithDefault<idx_t>(209, "probe_child", result->probe_child);
	deserializer.ReadPropertyWithDefault<idx_t>(210, "left_column_count", result->left_column_count);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(211, "owner_key_indices", result->owner_key_indices);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(212, "probe_key_indices", result->probe_key_indices);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(213, "owner_payload_indices", result->owner_payload_indices);
	deserializer.ReadPropertyWithDefault<vector<HashGroupJoinOutputSource>>(214, "output_group_sources", result->output_group_sources);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(215, "output_group_indices", result->output_group_indices);
	deserializer.ReadProperty<HashGroupJoinUnmatchedPolicy>(216, "unmatched_policy", result->unmatched_policy);
	deserializer.ReadPropertyWithExplicitDefault<bool>(217, "routed", result->routed, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(218, "unique_owner", result->unique_owner, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(219, "single_match", result->single_match, false);
	auto use_index = deserializer.ReadPropertyWithExplicitDefault<bool>(220, "use_index", false);
	deserializer.ReadPropertyWithExplicitDefault<GroupJoinExecutionMode>(221, "execution_mode", result->execution_mode, GroupJoinExecutionMode::AUTO);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(222, "estimated_owner_rows", result->estimated_owner_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(223, "estimated_probe_rows", result->estimated_probe_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(224, "estimated_match_rows", result->estimated_match_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(225, "estimated_matched_groups", result->estimated_matched_groups, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(226, "estimated_distinct_probe_keys", result->estimated_distinct_probe_keys, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(227, "separate_cost", result->separate_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(228, "eager_cost", result->eager_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(229, "memoizing_cost", result->memoizing_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(230, "index_cost", result->index_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<Value>(231, "perfect_min", result->perfect_min, Value());
	deserializer.ReadPropertyWithExplicitDefault<Value>(232, "perfect_max", result->perfect_max, Value());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(233, "perfect_range", result->perfect_range, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(234, "physical_eager_cost", result->physical_eager_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<GroupJoinImplementation>(235, "implementation", result->implementation, GroupJoinImplementation::MEMOIZING_HASH);
	deserializer.ReadPropertyWithExplicitDefault<double>(236, "perfect_cost", result->perfect_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<vector<idx_t>>(237, "factorized_driver_key_indices", result->factorized_driver_key_indices, {});
	deserializer.ReadPropertyWithExplicitDefault<vector<idx_t>>(238, "factorized_left_key_indices", result->factorized_left_key_indices, {});
	deserializer.ReadPropertyWithExplicitDefault<vector<idx_t>>(239, "factorized_right_key_indices", result->factorized_right_key_indices, {});
	deserializer.ReadPropertyWithExplicitDefault<vector<FactorizedAggregateSource>>(240, "factorized_aggregate_sources", result->factorized_aggregate_sources, {});
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(241, "factorized_driver_column_count", result->factorized_driver_column_count, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(242, "factorized_left_column_count", result->factorized_left_column_count, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(243, "estimated_left_factor_rows", result->estimated_left_factor_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(244, "estimated_right_factor_rows", result->estimated_right_factor_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<bool>(245, "factorized_preserve_left", result->factorized_preserve_left, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(246, "factorized_preserve_right", result->factorized_preserve_right, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(247, "factorized_semi_left", result->factorized_semi_left, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(248, "factorized_semi_right", result->factorized_semi_right, false);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(249, "estimated_factorized_join_rows", result->estimated_factorized_join_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(250, "estimated_factorized_matched_drivers", result->estimated_factorized_matched_drivers, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(251, "estimated_left_factor_scan_rows", result->estimated_left_factor_scan_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(252, "estimated_right_factor_scan_rows", result->estimated_right_factor_scan_rows, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(253, "factorized_build_cost", result->factorized_build_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(254, "factorized_probe_cost", result->factorized_probe_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(255, "factorized_scan_cost", result->factorized_scan_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(256, "factorized_routing_cost", result->factorized_routing_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(257, "factorized_spill_cost", result->factorized_spill_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(258, "factorized_cost", result->factorized_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(259, "factorized_best_existing_cost", result->factorized_best_existing_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<bool>(260, "factorized_cost_reliable", result->factorized_cost_reliable, false);
	deserializer.ReadPropertyWithExplicitDefault<bool>(261, "factorized_auto_selected", result->factorized_auto_selected, false);
	deserializer.ReadPropertyWithExplicitDefault<double>(262, "factorized_filter_cost", result->factorized_filter_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(263, "factorized_cache_cost", result->factorized_cache_cost, 0);
	deserializer.ReadPropertyWithExplicitDefault<double>(264, "factorized_eager_work_cost", result->factorized_eager_work_cost, 0);
	if (use_index && result->implementation == GroupJoinImplementation::MEMOIZING_HASH) {
		result->implementation = GroupJoinImplementation::INDEX;
	}
	return std::move(result);
}

void LogicalInsert::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info", table.GetInfo());
	serializer.WritePropertyWithDefault<vector<vector<unique_ptr<Expression>>>>(201, "insert_values", insert_values);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<IndexVector<idx_t, PhysicalIndex>>(202, "column_index_map", column_index_map, IndexVector<idx_t, PhysicalIndex>());
	} else {
		serializer.WriteProperty<IndexVector<idx_t, PhysicalIndex>>(202, "column_index_map", column_index_map);
	}
	serializer.WritePropertyWithDefault<vector<LogicalType>>(203, "expected_types", expected_types);
	serializer.WritePropertyWithDefault<TableIndex>(204, "table_index", table_index);
	serializer.WritePropertyWithDefault<bool>(205, "return_chunk", return_chunk);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(206, "bound_defaults", bound_defaults);
	serializer.WriteProperty<OnConflictAction>(207, "action_type", on_conflict_info.action_type);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(208, "expected_set_types", on_conflict_info.expected_set_types);
	serializer.WritePropertyWithDefault<unordered_set<idx_t>>(209, "on_conflict_filter", on_conflict_info.on_conflict_filter);
	serializer.WritePropertyWithDefault<unique_ptr<Expression>>(210, "on_conflict_condition", on_conflict_info.on_conflict_condition);
	serializer.WritePropertyWithDefault<unique_ptr<Expression>>(211, "do_update_condition", on_conflict_info.do_update_condition);
	serializer.WritePropertyWithDefault<vector<PhysicalIndex>>(212, "set_columns", on_conflict_info.set_columns);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(213, "set_types", on_conflict_info.set_types);
	serializer.WritePropertyWithDefault<TableIndex>(214, "excluded_table_index", on_conflict_info.excluded_table_index);
	serializer.WritePropertyWithDefault<vector<column_t>>(215, "columns_to_fetch", on_conflict_info.columns_to_fetch);
	serializer.WritePropertyWithDefault<vector<column_t>>(216, "source_columns", on_conflict_info.source_columns);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(217, "expressions", expressions);
	serializer.WritePropertyWithDefault<bool>(218, "update_is_del_and_insert", on_conflict_info.update_is_del_and_insert, false);
}

unique_ptr<LogicalOperator> LogicalInsert::Deserialize(Deserializer &deserializer) {
	auto table_info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info");
	auto result = duckdb::unique_ptr<LogicalInsert>(new LogicalInsert(deserializer.Get<ClientContext &>(), std::move(table_info)));
	deserializer.ReadPropertyWithDefault<vector<vector<unique_ptr<Expression>>>>(201, "insert_values", result->insert_values);
	deserializer.ReadPropertyWithExplicitDefault<IndexVector<idx_t, PhysicalIndex>>(202, "column_index_map", result->column_index_map, IndexVector<idx_t, PhysicalIndex>());
	deserializer.ReadPropertyWithDefault<vector<LogicalType>>(203, "expected_types", result->expected_types);
	deserializer.ReadPropertyWithDefault<TableIndex>(204, "table_index", result->table_index);
	deserializer.ReadPropertyWithDefault<bool>(205, "return_chunk", result->return_chunk);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(206, "bound_defaults", result->bound_defaults);
	deserializer.ReadProperty<OnConflictAction>(207, "action_type", result->on_conflict_info.action_type);
	deserializer.ReadPropertyWithDefault<vector<LogicalType>>(208, "expected_set_types", result->on_conflict_info.expected_set_types);
	deserializer.ReadPropertyWithDefault<unordered_set<idx_t>>(209, "on_conflict_filter", result->on_conflict_info.on_conflict_filter);
	deserializer.ReadPropertyWithDefault<unique_ptr<Expression>>(210, "on_conflict_condition", result->on_conflict_info.on_conflict_condition);
	deserializer.ReadPropertyWithDefault<unique_ptr<Expression>>(211, "do_update_condition", result->on_conflict_info.do_update_condition);
	deserializer.ReadPropertyWithDefault<vector<PhysicalIndex>>(212, "set_columns", result->on_conflict_info.set_columns);
	deserializer.ReadPropertyWithDefault<vector<LogicalType>>(213, "set_types", result->on_conflict_info.set_types);
	deserializer.ReadPropertyWithDefault<TableIndex>(214, "excluded_table_index", result->on_conflict_info.excluded_table_index);
	deserializer.ReadPropertyWithDefault<vector<column_t>>(215, "columns_to_fetch", result->on_conflict_info.columns_to_fetch);
	deserializer.ReadPropertyWithDefault<vector<column_t>>(216, "source_columns", result->on_conflict_info.source_columns);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(217, "expressions", result->expressions);
	deserializer.ReadPropertyWithExplicitDefault<bool>(218, "update_is_del_and_insert", result->on_conflict_info.update_is_del_and_insert, false);
	return std::move(result);
}

void LogicalLimit::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WriteProperty<BoundLimitNode>(200, "limit_val", limit_val);
	serializer.WriteProperty<BoundLimitNode>(201, "offset_val", offset_val);
}

unique_ptr<LogicalOperator> LogicalLimit::Deserialize(Deserializer &deserializer) {
	auto limit_val = deserializer.ReadProperty<BoundLimitNode>(200, "limit_val");
	auto offset_val = deserializer.ReadProperty<BoundLimitNode>(201, "offset_val");
	auto result = duckdb::unique_ptr<LogicalLimit>(new LogicalLimit(std::move(limit_val), std::move(offset_val)));
	return std::move(result);
}

void LogicalLoad::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<LoadInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalLoad::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalLoad>(new LogicalLoad(std::move(info)));
	return std::move(result);
}

void LogicalMaterializedCTE::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
	serializer.WritePropertyWithDefault<idx_t>(201, "column_count", column_count);
	serializer.WritePropertyWithDefault<Identifier>(202, "ctename", ctename);
	serializer.WritePropertyWithDefault<CTEMaterialize>(203, "materialize", materialize, CTEMaterialize::CTE_MATERIALIZE_DEFAULT);
}

unique_ptr<LogicalOperator> LogicalMaterializedCTE::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalMaterializedCTE>(new LogicalMaterializedCTE());
	deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index", result->table_index);
	deserializer.ReadPropertyWithDefault<idx_t>(201, "column_count", result->column_count);
	deserializer.ReadPropertyWithDefault<Identifier>(202, "ctename", result->ctename);
	deserializer.ReadPropertyWithExplicitDefault<CTEMaterialize>(203, "materialize", result->materialize, CTEMaterialize::CTE_MATERIALIZE_DEFAULT);
	return std::move(result);
}

void LogicalMergeInto::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info", table.GetInfo());
	serializer.WritePropertyWithDefault<TableIndex>(201, "table_index", table_index);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(202, "bound_defaults", bound_defaults);
	serializer.WritePropertyWithDefault<idx_t>(203, "row_id_start", row_id_start);
	serializer.WriteProperty<optional_idx>(204, "source_marker", source_marker);
	serializer.WritePropertyWithDefault<map<MergeActionCondition, vector<unique_ptr<BoundMergeIntoAction>>>>(205, "actions", actions);
	serializer.WritePropertyWithDefault<bool>(206, "return_chunk", return_chunk);
	serializer.WritePropertyWithDefault<vector<idx_t>>(207, "delete_return_columns", delete_return_columns);
}

unique_ptr<LogicalOperator> LogicalMergeInto::Deserialize(Deserializer &deserializer) {
	auto table_info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info");
	auto result = duckdb::unique_ptr<LogicalMergeInto>(new LogicalMergeInto(deserializer.Get<ClientContext &>(), table_info));
	deserializer.ReadPropertyWithDefault<TableIndex>(201, "table_index", result->table_index);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(202, "bound_defaults", result->bound_defaults);
	deserializer.ReadPropertyWithDefault<idx_t>(203, "row_id_start", result->row_id_start);
	deserializer.ReadProperty<optional_idx>(204, "source_marker", result->source_marker);
	deserializer.ReadPropertyWithDefault<map<MergeActionCondition, vector<unique_ptr<BoundMergeIntoAction>>>>(205, "actions", result->actions);
	deserializer.ReadPropertyWithDefault<bool>(206, "return_chunk", result->return_chunk);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(207, "delete_return_columns", result->delete_return_columns);
	return std::move(result);
}

void LogicalOrder::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<vector<BoundOrderByNode>>(200, "orders", orders);
	serializer.WritePropertyWithDefault<vector<ProjectionIndex>>(201, "projections", projection_map);
}

unique_ptr<LogicalOperator> LogicalOrder::Deserialize(Deserializer &deserializer) {
	auto orders = deserializer.ReadPropertyWithDefault<vector<BoundOrderByNode>>(200, "orders");
	auto result = duckdb::unique_ptr<LogicalOrder>(new LogicalOrder(std::move(orders)));
	deserializer.ReadPropertyWithDefault<vector<ProjectionIndex>>(201, "projections", result->projection_map);
	return std::move(result);
}

void LogicalPivot::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "pivot_index", pivot_index);
	serializer.WriteProperty<BoundPivotInfo>(201, "bound_pivot", bound_pivot);
}

unique_ptr<LogicalOperator> LogicalPivot::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalPivot>(new LogicalPivot());
	deserializer.ReadPropertyWithDefault<TableIndex>(200, "pivot_index", result->pivot_index);
	deserializer.ReadProperty<BoundPivotInfo>(201, "bound_pivot", result->bound_pivot);
	return std::move(result);
}

void LogicalPositionalJoin::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
}

unique_ptr<LogicalOperator> LogicalPositionalJoin::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalPositionalJoin>(new LogicalPositionalJoin());
	return std::move(result);
}

void LogicalProjection::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(201, "expressions", expressions);
}

unique_ptr<LogicalOperator> LogicalProjection::Deserialize(Deserializer &deserializer) {
	auto table_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index");
	auto expressions = deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(201, "expressions");
	auto result = duckdb::unique_ptr<LogicalProjection>(new LogicalProjection(table_index, std::move(expressions)));
	return std::move(result);
}

void LogicalRecursiveCTE::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<bool>(200, "union_all", union_all);
	serializer.WritePropertyWithDefault<Identifier>(201, "ctename", ctename);
	serializer.WritePropertyWithDefault<TableIndex>(202, "table_index", table_index);
	serializer.WritePropertyWithDefault<idx_t>(203, "column_count", column_count);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(204, "key_targets", key_targets);
	serializer.WritePropertyWithDefault<bool>(205, "ref_recurring", ref_recurring);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(206, "payload_aggregates", payload_aggregates);
	serializer.WritePropertyWithDefault<vector<LogicalType>>(207, "internal_types", internal_types);
}

unique_ptr<LogicalOperator> LogicalRecursiveCTE::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalRecursiveCTE>(new LogicalRecursiveCTE());
	deserializer.ReadPropertyWithDefault<bool>(200, "union_all", result->union_all);
	deserializer.ReadPropertyWithDefault<Identifier>(201, "ctename", result->ctename);
	deserializer.ReadPropertyWithDefault<TableIndex>(202, "table_index", result->table_index);
	deserializer.ReadPropertyWithDefault<idx_t>(203, "column_count", result->column_count);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(204, "key_targets", result->key_targets);
	deserializer.ReadPropertyWithDefault<bool>(205, "ref_recurring", result->ref_recurring);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(206, "payload_aggregates", result->payload_aggregates);
	deserializer.ReadPropertyWithDefault<vector<LogicalType>>(207, "internal_types", result->internal_types);
	return std::move(result);
}

void LogicalReset::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<Identifier>(200, "name", name);
	serializer.WriteProperty<SetScope>(201, "scope", scope);
}

unique_ptr<LogicalOperator> LogicalReset::Deserialize(Deserializer &deserializer) {
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(200, "name");
	auto scope = deserializer.ReadProperty<SetScope>(201, "scope");
	auto result = duckdb::unique_ptr<LogicalReset>(new LogicalReset(std::move(name), scope));
	return std::move(result);
}

void LogicalSample::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<SampleOptions>>(200, "sample_options", sample_options);
}

unique_ptr<LogicalOperator> LogicalSample::Deserialize(Deserializer &deserializer) {
	auto result = duckdb::unique_ptr<LogicalSample>(new LogicalSample());
	deserializer.ReadPropertyWithDefault<unique_ptr<SampleOptions>>(200, "sample_options", result->sample_options);
	return std::move(result);
}

void LogicalSet::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<Identifier>(200, "name", name);
	serializer.WriteProperty<Value>(201, "value", value);
	serializer.WriteProperty<SetScope>(202, "scope", scope);
}

unique_ptr<LogicalOperator> LogicalSet::Deserialize(Deserializer &deserializer) {
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(200, "name");
	auto value = deserializer.ReadProperty<Value>(201, "value");
	auto scope = deserializer.ReadProperty<SetScope>(202, "scope");
	auto result = duckdb::unique_ptr<LogicalSet>(new LogicalSet(std::move(name), value, scope));
	return std::move(result);
}

void LogicalSetOperation::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "table_index", table_index);
	serializer.WritePropertyWithDefault<idx_t>(201, "column_count", column_count);
	serializer.WritePropertyWithDefault<bool>(202, "setop_all", setop_all, true);
	serializer.WritePropertyWithDefault<bool>(203, "allow_out_of_order", allow_out_of_order, true);
}

unique_ptr<LogicalOperator> LogicalSetOperation::Deserialize(Deserializer &deserializer) {
	auto table_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "table_index");
	auto column_count = deserializer.ReadPropertyWithDefault<idx_t>(201, "column_count");
	auto setop_all = deserializer.ReadPropertyWithExplicitDefault<bool>(202, "setop_all", true);
	auto allow_out_of_order = deserializer.ReadPropertyWithExplicitDefault<bool>(203, "allow_out_of_order", true);
	auto result = duckdb::unique_ptr<LogicalSetOperation>(new LogicalSetOperation(table_index, column_count, deserializer.Get<LogicalOperatorType>(), setop_all, allow_out_of_order));
	return std::move(result);
}

void LogicalTopN::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<vector<BoundOrderByNode>>(200, "orders", orders);
	serializer.WritePropertyWithDefault<idx_t>(201, "limit", limit);
	serializer.WritePropertyWithDefault<idx_t>(202, "offset", offset);
}

unique_ptr<LogicalOperator> LogicalTopN::Deserialize(Deserializer &deserializer) {
	auto orders = deserializer.ReadPropertyWithDefault<vector<BoundOrderByNode>>(200, "orders");
	auto limit = deserializer.ReadPropertyWithDefault<idx_t>(201, "limit");
	auto offset = deserializer.ReadPropertyWithDefault<idx_t>(202, "offset");
	auto result = duckdb::unique_ptr<LogicalTopN>(new LogicalTopN(std::move(orders), limit, offset));
	return std::move(result);
}

void LogicalTransaction::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<TransactionInfo>>(200, "info", info);
}

unique_ptr<LogicalOperator> LogicalTransaction::Deserialize(Deserializer &deserializer) {
	auto info = deserializer.ReadPropertyWithDefault<unique_ptr<ParseInfo>>(200, "info");
	auto result = duckdb::unique_ptr<LogicalTransaction>(new LogicalTransaction(std::move(info)));
	return std::move(result);
}

void LogicalUnnest::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "unnest_index", unnest_index);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(201, "expressions", expressions);
}

unique_ptr<LogicalOperator> LogicalUnnest::Deserialize(Deserializer &deserializer) {
	auto unnest_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "unnest_index");
	auto result = duckdb::unique_ptr<LogicalUnnest>(new LogicalUnnest(unnest_index));
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(201, "expressions", result->expressions);
	return std::move(result);
}

void LogicalUpdate::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info", table.GetInfo());
	serializer.WritePropertyWithDefault<TableIndex>(201, "table_index", table_index);
	serializer.WritePropertyWithDefault<bool>(202, "return_chunk", return_chunk);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(203, "expressions", expressions);
	serializer.WritePropertyWithDefault<vector<PhysicalIndex>>(204, "columns", columns);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(205, "bound_defaults", bound_defaults);
	serializer.WritePropertyWithDefault<bool>(206, "update_is_del_and_insert", update_is_del_and_insert);
	serializer.WritePropertyWithDefault<bool>(207, "capture_old_rows", capture_old_rows, false);
	serializer.WritePropertyWithDefault<vector<idx_t>>(208, "old_row_columns", old_row_columns);
	serializer.WritePropertyWithDefault<RowIdHandling>(209, "row_id_handling", row_id_handling, RowIdHandling::ASSUME_UNIQUE);
}

unique_ptr<LogicalOperator> LogicalUpdate::Deserialize(Deserializer &deserializer) {
	auto table_info = deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(200, "table_info");
	auto result = duckdb::unique_ptr<LogicalUpdate>(new LogicalUpdate(deserializer.Get<ClientContext &>(), table_info));
	deserializer.ReadPropertyWithDefault<TableIndex>(201, "table_index", result->table_index);
	deserializer.ReadPropertyWithDefault<bool>(202, "return_chunk", result->return_chunk);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(203, "expressions", result->expressions);
	deserializer.ReadPropertyWithDefault<vector<PhysicalIndex>>(204, "columns", result->columns);
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(205, "bound_defaults", result->bound_defaults);
	deserializer.ReadPropertyWithDefault<bool>(206, "update_is_del_and_insert", result->update_is_del_and_insert);
	deserializer.ReadPropertyWithExplicitDefault<bool>(207, "capture_old_rows", result->capture_old_rows, false);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(208, "old_row_columns", result->old_row_columns);
	deserializer.ReadPropertyWithExplicitDefault<RowIdHandling>(209, "row_id_handling", result->row_id_handling, RowIdHandling::ASSUME_UNIQUE);
	return std::move(result);
}

void LogicalWindow::Serialize(Serializer &serializer) const {
	LogicalOperator::Serialize(serializer);
	serializer.WritePropertyWithDefault<TableIndex>(200, "window_index", window_index);
	serializer.WritePropertyWithDefault<vector<unique_ptr<Expression>>>(201, "expressions", expressions);
}

unique_ptr<LogicalOperator> LogicalWindow::Deserialize(Deserializer &deserializer) {
	auto window_index = deserializer.ReadPropertyWithDefault<TableIndex>(200, "window_index");
	auto result = duckdb::unique_ptr<LogicalWindow>(new LogicalWindow(window_index));
	deserializer.ReadPropertyWithDefault<vector<unique_ptr<Expression>>>(201, "expressions", result->expressions);
	return std::move(result);
}

} // namespace duckdb
